apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: nginx-app
    valuesFile: values.yaml
    namespace: nginx
    releaseName: nginx-app
