apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: nginx-app
    path: ../../charts/nginx-app
    releaseName: nginx-app
    valuesFile: values.yaml
