apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Values.message }}</title>
    </head>
    <body>
      <h1>{{ .Values.message }}</h1>
    </body>
    </html>
